apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-ingress-controller
spec:
  template:
    spec:
      containers:
        - name: alb-ingress-controller
          args:
          - --ingress-class=alb
          - --cluster-name=translatorapp-cluster
          - --aws-region=ap-northeast-1
          # Set a cluster VPC ID
          - --aws-vpc-id=<Cluster VPC ID>
