apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: translatorapp-cluster
  region: ap-northeast-1
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: fp-translatorapp
    selectors:
      - namespace: translatorapp
iam:
  withOIDC: true

