# Ref. https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: translatorapp

commonLabels:
  app/name: translatorapp
  app/infra: gce
  app/env: example

resources:
- namespace.yaml
- api-config-env.yaml
- api-secrets-env.yaml
- api-secrets-file.yaml
- api-service.yaml
- envoy-config-file.yaml
- envoy-service.yaml
- envoy-backendconfig.yaml
- ingress-cert.yaml
- ingress.yaml

patches:
# Overwrite a container image name.
- path: api-patch.yaml
  target:
    kind: Deployment
    name: api-deployment
# Overwrite domain properties.
- path: ingress-cert-patch.yaml
  target:
    kind: ManagedCertificate
# Overwrite ingress properties.
- path: ingress-patch.yaml
  target:
    kind: Ingress



