apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: translatorapp
  labels:
    app/role: translatorapp-api-service
spec:
  type: NodePort
  selector:
    app/role: translatorapp-api-pod
  ports:
    - port: 50051
      protocol: TCP
      name: grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: translatorapp
  labels:
    app/role: translatorapp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      # Uses api-pod
      app/role: translatorapp-api-pod
  # Pod
  template:
    metadata:
      name: api-pod
      namespace: translatorapp
      labels:
        app/role: translatorapp-api-pod
    spec:
      containers:
        - name: api-pod
          # Set ECR image name
          # e.g. image: <AWS account>.dkr.ecr.ap-northeast-1.amazonaws.com/translatorapp-api:latest
          image: 1234566.dkr.ecr.ap-northeast-1.amazonaws.com/translatorapp-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
          envFrom:
            - configMapRef:
                name: api-config-env
            - secretRef:
                name: api-secrets-env
          volumeMounts:
            - name: secrets
              mountPath: /app/certs
      volumes:
        - name: secrets
          secret:
            secretName: api-secrets-file
