apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  namespace: translatorapp
  labels:
    app/role: translatorapp-envoy-service
spec:
  type: NodePort
  selector:
    app/role: translatorapp-envoy-pod
  sessionAffinity: None
  ports:
  - name: http
    port: 9000
    targetPort: http
    protocol: TCP
  - name: envoy-admin
    port: 9901
    targetPort: envoy-admin
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enovy-deployment
  namespace: translatorapp
  labels:
    app/role: translatorapp-envoy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app/role: translatorapp-envoy-pod
  template:
    metadata:
      labels:
        app/role: translatorapp-envoy-pod
    spec:
      containers:
        - name: translatorapp-envoy-pod
          image: envoyproxy/envoy:v1.16.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
            - name: envoy-admin
              containerPort: 9901
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
      volumes:
        - name: config
          configMap:
            name: envoy-configmap
