// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/app/util/di/di.go

// Package di is a generated GoMock package.
package di

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDI is a mock of DI interface
type MockDI struct {
	ctrl     *gomock.Controller
	recorder *MockDIMockRecorder
}

// MockDIMockRecorder is the mock recorder for MockDI
type MockDIMockRecorder struct {
	mock *MockDI
}

// NewMockDI creates a new mock instance
func NewMockDI(ctrl *gomock.Controller) *MockDI {
	mock := &MockDI{ctrl: ctrl}
	mock.recorder = &MockDIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDI) EXPECT() *MockDIMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockDI) Get(name string, args ...interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockDIMockRecorder) Get(name interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDI)(nil).Get), varargs...)
}
