// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/app/util/log/logger.go

// Package log is a generated GoMock package.
package log

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// SetLevel mocks base method
func (m *MockLogger) SetLevel(level Level) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLevel", level)
}

// SetLevel indicates an expected call of SetLevel
func (mr *MockLoggerMockRecorder) SetLevel(level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLevel", reflect.TypeOf((*MockLogger)(nil).SetLevel), level)
}

// Debug mocks base method
func (m *MockLogger) Debug(ctx context.Context, v Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", ctx, v)
}

// Debug indicates an expected call of Debug
func (mr *MockLoggerMockRecorder) Debug(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), ctx, v)
}

// Info mocks base method
func (m *MockLogger) Info(ctx context.Context, v Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", ctx, v)
}

// Info indicates an expected call of Info
func (mr *MockLoggerMockRecorder) Info(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), ctx, v)
}

// Error mocks base method
func (m *MockLogger) Error(ctx context.Context, v Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", ctx, v)
}

// Error indicates an expected call of Error
func (mr *MockLoggerMockRecorder) Error(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), ctx, v)
}

// Fatal mocks base method
func (m *MockLogger) Fatal(v Value) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", v)
}

// Fatal indicates an expected call of Fatal
func (mr *MockLoggerMockRecorder) Fatal(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), v)
}
