# Ref. https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: translatorapp

commonLabels:
  app/env: example
  app/infra: gce
  app/name: translatorapp

resources:
- api-service.yaml
